//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabControl.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class El_AbayEntities : DbContext
    {
        public El_AbayEntities()
            : base("name=El_AbayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tmp_esf_Invoice> tmp_esf_Invoice { get; set; }
        public virtual DbSet<tmp_esf_ProductSet> tmp_esf_ProductSet { get; set; }
        public virtual DbSet<tmp_esf_Seller> tmp_esf_Seller { get; set; }
    }
}
