//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_esf_Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmp_esf_Seller()
        {
            this.tmp_esf_Invoice = new HashSet<tmp_esf_Invoice>();
        }
    
        public byte Id { get; set; }
        public System.DateTime WorkMonth { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string bank { get; set; }
        public string bik { get; set; }
        public string certificateNum { get; set; }
        public string certificateSeries { get; set; }
        public string iik { get; set; }
        public string kbe { get; set; }
        public string tin { get; set; }
        public string Director { get; set; }
        public string Accountant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmp_esf_Invoice> tmp_esf_Invoice { get; set; }
    }
}
