//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_esf_ProductSet
    {
        public int NewID { get; set; }
        public int Id { get; set; }
        public int InvoiceNumber { get; set; }
        public string currencyCode { get; set; }
        public string description { get; set; }
        public string ndsAmount { get; set; }
        public string ndsRate { get; set; }
        public string priceWithTax { get; set; }
        public string priceWithoutTax { get; set; }
        public string quantity { get; set; }
        public string turnoverSize { get; set; }
        public string unitCode { get; set; }
        public string unitNomenclature { get; set; }
        public string unitPrice { get; set; }
        public string truOriginCode { get; set; }
    }
}
